### ISSUE TITLE
[raudio] Makefile not setting the appropriate macros to enable audio on Android

### ISSUE THREAD

**Issue by futureapricot** [raysan5/raylib#2118]
When working in Android and compiling Raylib from source, the audio backend is detected as NULL and the app remains silent despite sound/music being loaded correctly, as `InitAudioDevice()` logs:
```
AUDIO: Device initialized successfully
     > Backend:       miniaudio / Null
     > Format:        32-bit IEEE Floating Point -> 32-bit IEEE Floating Point
     > Channels:      2 -> 2
     > Sample rate:   48000 -> 48000
     > Periods size:  1440
```

After some testing I discovered that `miniaudio.h` requires to set the macros `MA_SUPPORT_AAUDIO` and `MA_ENABLE_AAUDIO` to enable audio when compiling for Android.

None of them are set neither in the Makefile or in `raudio.c` so default builds for Android have the audio disabled. Setting both macros is enough to enable audio in Android.

###### Tested on Linux
Host OS: Solus Linux
Android NDK: 23.1.7779620
Target SDK: 31
Android Studio: 2020.3.1 Patch 2
CMake : v3.18.1 (Bundled with Android Studio)

Compiled from source for Android with the following line
```bash
make raylib PLATFORM=PLATFORM_ANDROID RAYLIB_BUILD_MODE=DEBUG RAYLIB_LIBTYPE=STATIC ANDROID_ARCH=ARM64 ANDROID_API=31
```

**Comment by raysan5** [comment]
@futureapricot Atually those macros should be automatically enabled by `miniaudio`, no need for a manual setup. Maybe @mackron has some idea about this possible issue?

**Comment by mackron** [comment]
Both Android backends (OpenSL and AAudio) should be enabled by default unless MA_DISABLE_* is used. Something helpful might be to enable MA_DEBUG_OUTPUT and post the output here.

**Comment by futureapricot** [comment]
I tried enabling `MA_DEBUG_OUTPUT` but it didn't print any debug log on Android. It seems that `MA_ANDROID` is not being set neither.

Enabling both `MA_DEBUG_OUTPUT` and `MA_ANDROID` gives the following compiler error:
```bash
/opt/Android/Sdk/ndk/23.1.7779620/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android31-clang -c raudio.c -Wall -D_DEFAULT_SOURCE -Wno-missing-braces -Werror=pointer-arith -fno-strict-aliasing -std=c99 -g -target aarch64 -mfix-cortex-a53-835769 -ffunction-sections -funwind-tables -fstack-protector-strong -fPIE -fPIC -Wa,--noexecstack -Wformat -no-canonical-prefixes -DANDROID -DPLATFORM_ANDROID -D__ANDROID_API__=31 -DMAL_NO_OSS -DMA_DEBUG_OUTPUT -DMA_ANDROID  -I. -Iexternal/glfw/include -Iexternal/glfw/deps/mingw -I/opt/Android/Sdk/ndk/23.1.7779620/sources/android/native_app_glue -I/opt/Android/Sdk/ndk/23.1.7779620/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/include -I/opt/Android/Sdk/ndk/23.1.7779620/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/include/aarch64-linux-android -DPLATFORM_ANDROID
In file included from raudio.c:167:
./external/miniaudio.h:8509:9: warning: implicit declaration of function '__android_log_print' is invalid in C99 [-Wimplicit-function-declaration]
        __android_log_print(ANDROID_LOG_DEBUG, MA_ANDROID_LOG_TAG, "%s: %s", ma_log_level_to_string(level), pMessage);
        ^
./external/miniaudio.h:8509:29: error: use of undeclared identifier 'ANDROID_LOG_DEBUG'
        __android_log_print(ANDROID_LOG_DEBUG, MA_ANDROID_LOG_TAG, "%s: %s", ma_log_level_to_string(level), pMessage);
```

Enabling `MA_ANDROID` also didn't enabled audio, `MA_SUPPORT_AAUDIO` alone was enough for the device to enable AAudio backend.


It may be obvious but useful to know that am compiling Raylib on Linux, then linking it with an Android Studio project and testing in two physical devices within Android Studio. Both devices are SDK29 and SDK30 respectively and in both the log output is the same

Let me know if you need more information.

**Comment by mackron** [comment]
OK, that's your problem. If you're compiling on Linux, only Linux backends will be compiled in, none of which will work on Android. There is no way to enable non-Linux backends when building on Linux.

**Comment by sogaiu** [comment]
For future reference, with the following diff to Raylib's [current Makefile](https://github.com/raysan5/raylib/blob/7fa75cb24e8fcc5983644276f9feed670e1f79c3/src/Makefile#L535-L540) I had success getting audio to work on Android with Raylib (all compilation done on a Linux box using a modified raylib-game-template setup):
```
diff --git a/src/Makefile b/src/Makefile
index 87d76a65..fc5d171e 100644
--- a/src/Makefile
+++ b/src/Makefile
@@ -535,6 +535,10 @@ ifeq ($(RAYLIB_MODULE_MODELS),TRUE)
 endif
 ifeq ($(RAYLIB_MODULE_AUDIO),TRUE)
     OBJS += raudio.o
+    # XXX: https://github.com/raysan5/raylib/issues/2118
+    ifeq ($(PLATFORM),PLATFORM_ANDROID)
+      CFLAGS += -DMA_SUPPORT_AAUDIO
+    endif
 endif
 ifeq ($(RAYLIB_MODULE_RAYGUI),TRUE)
     OBJS += raygui.o
```

Thanks to all participants of this issue :+1:

**Comment by mackron** [comment]
Explicitly defining `MA_SUPPORT_AAUDIO` on the command line is completely unsupported. That's an internal define for use by miniaudio internally. The proper way to build the Android build is through an Android toolchain such as Android Studio.

**Comment by sogaiu** [comment]
Thanks for the info.

I adapted the instructions given at the raylib repository's Wiki along with the raylib-game-template repository:

* https://github.com/raysan5/raylib/wiki/Working-for-Android
* https://github.com/raysan5/raylib/wiki/Working-for-Android-(on-Linux)
* https://github.com/raysan5/raylib-game-template/blob/main/src/Makefile.Android

Though these do not use Android Studio, they do use the NDK.

I'm interested in using a supported method, but at this point would rather not switch to using Android Studio.

Any tips would be appreciated.

**Comment by seprab** [comment]
Hey, I just tested the workaround on Windows and it's working!

**Comment by Maor2871** [comment]
Hey, I'm currently facing the same issue of `miniaudio / Null`.
I work on windows, and followed the steps in: [https://github.com/raysan5/raylib/wiki/Working-for-Android](url).
My app runs as expected, but with no sound.
I don't use android studios, and the workaround didn't do the job.
I tried to edit `miniaudio.h` by adding 
`#define MA_SUPPORT_AAUDIO`
`#define MA_ENABLE_AAUDIO`
but with no success.
I also tried @sogaiu suggestion and added `CFLAGS += -DMA_SUPPORT_AAUDIO` to `raylib/src/Makefile`.
I didn't forget to recompile raylib source code with `mingw32-make PLATFORM=PLATFORM_ANDROID` after each modification.
Any ideas? I would happily share more details if you find them relevant.

**Comment by sogaiu** [comment]
I never tried on Windows, but perhaps @seprab might have some tips?

**Comment by mackron** [comment]
Are you compiling with an Android toolchain? You need to compile with a proper Android compiler. No other configuration is supported by miniaudio. You can't just compile on a Windows or Linux compiler and expect it to work on Android. The "workaround" mentioned above is working by coincidence, not by design.

**Comment by Maor2871** [comment]
I'm using the `Command line tools` package as described in [Working-for-Android](https://github.com/raysan5/raylib/wiki/Working-for-Android) under the Android SDK section. 
In the Makefile.Android i have theses settings:
`JAVA_HOME              ?= C:/open-jdk`
`ANDROID_HOME           ?= C:/android-sdk`
`ANDROID_NDK            ?= C:/android-ndk`
`ANDROID_TOOLCHAIN      ?= $(ANDROID_NDK)/toolchains/llvm/prebuilt/windows-x86_64`
`ANDROID_BUILD_TOOLS    ?= $(ANDROID_HOME)/build-tools/29.0.3`
`ANDROID_PLATFORM_TOOLS  = $(ANDROID_HOME)/platform-tools`

android-ndk was downloaded from: [https://developer.android.com/ndk/downloads/](https://developer.android.com/ndk/downloads/)

This process seems to do a pretty good job except to the sound issue, it's generating an apk and the app works great on my android device. Can it be versions mismatch or perhaps i have downloaded the wrong ndk package?
Are you familiar with different mechanism that can compile raylib app to android?
I have just downloaded android studios and it seems that even if it's possible to compile raylib app there, there are tons of modifications and setups required, and I cannot find any guidance on that anywhere.

Your help is much appreciated, thanks.

**Comment by mackron** [comment]
OK, that should work. Are you able to compile with `-DMA_DEBUG_OUTPUT` and post the log here so I can take a look? There might be an error in there that might explain what's going on.

**Comment by Maor2871** [comment]
Well, trying to enable `-DMA_DEBUG_OUTPUT` got me to understand that I have to `#define` inside `raudio.c` right before the `#include "external/miniaudio.h"` line. On the one hand I reached the same as @futureapricot in this regard and didn't manage to compile raylib source code with it. On the other hand, I realized this is the same spot I need to `#define` `MA_SUPPORT_AAUDIO `, and as for the others it did the work and my app runs with audio now:
`AUDIO: Device initialized successfully`
`    > Backend:       miniaudio / AAudio`
`    > Format:        32-bit IEEE Floating Point -> 32-bit IEEE Floating Point`
`    > Channels:      2 -> 2`
`    > Sample rate:   48000 -> 48000`
`    > Periods size:  1440`

I think it could be very helpful making this process work without the manual adjustments, or perhaps fixing it at the core without the workaround approach.

Thank you very much for your immediate help, I was about to give up :).
If you want me to help in any way debugging this issue I'm right here.

**Comment by lorenzo774** [comment]
I tried to define the macros but with no success.

```cpp
#define MA_SUPPORT_AAUDIO
#define MA_ENABLE_AAUDIO

#include "miniaudio.h"
#include "raylib.h"
```

I have a question that maybe is stupid, do I need to use miniaudio to manage audio for android or does raylib use it automatically?

**Comment by lorenzo774** [comment]
@Maor2871 I ```#define``` inside ```raudio.c``` as you said but I have to compile the source code (no success).

**Comment by mackron** [comment]
The detection of Android as the build system is very simple in miniaudio. It surprises me that it wouldn't get picked up automatically. Here's what it does:

```
#ifdef __ANDROID__
    #define MA_ANDROID
#endif
```

And then a bit further down:

```
#if defined(MA_ANDROID)
    #define MA_SUPPORT_AAUDIO
    #define MA_SUPPORT_OPENSL
#endif
```

One thing that does seem odd is that for some reason I've put that bottom section inside the Unix detection section (`MA_UNIX`) so I'm wondering if maybe that's what the compiler is skipping over the `MA_SUPPORT_AAUDIO` and `MA_SUPPORT_OPENSL` defines? I've pushed a change to the miniaudio dev branch - are you able to replace the version of miniaudio.h with that version and try again (with all of your workarounds removed)?

**Comment by Maor2871** [comment]
Hey @mackron, I have tested the new `miniaudio.h` after reversing `raudio.c` and it seems to be working!
I get `> Backend:       miniaudio / AAudio` as expected and the app indeed plays the sound.

@lorenzo774, The `#define MA_SUPPORT_AAUDIO` and `#define MA_ENABLE_AAUDIO` seems right, but note that `miniaudio.h` is inside the `external` folder, which is why you should enter: `#include "external/miniaudio.h"`. Hope this will do the trick, and if not maybe even better for you would be to download the updated `miniaudio.h` that @mackron edited.
Of course don't forget to compile and delete `libraylib.a` from your `android.<project name>/lib/arm64-v8a` folder before you create the apk file.

**Comment by mackron** [comment]
Thanks for checking that. Good to hear. Just waiting on confirmation for another fix and will then get this released.

**Comment by lorenzo774** [comment]
@Maor2871 ```miniaudio.h``` is already included using the Makefile, I updated miniaudio using @mackron changes.
Still doesn't work.

**Comment by mackron** [comment]
@lorenzo774 I'm suspecting your issue might be different. Can you post a log of some kind? Maybe compile with the `-DMA_DEBUG_OUTPUT` option.

**Comment by lorenzo774** [comment]
@mackron 
```
--------- beginning of crash
--------- beginning of system
--------- beginning of main
10-23 23:53:52.007 22056 22103 I raylib  : SYSTEM: Decompress data: Comp. size: 1031 -> Original size: 131072
10-23 23:53:52.007 22056 22103 W raylib  : TEXTURE: Failed to load texture
10-23 23:53:52.009 22056 22103 I raylib  : AUDIO: Device initialized successfully
10-23 23:53:52.009 22056 22103 I raylib  :     > Backend:       miniaudio / Null
10-23 23:53:52.009 22056 22103 I raylib  :     > Format:        32-bit IEEE Floating Point -> 32-bit IEEE Floating Point
10-23 23:53:52.009 22056 22103 I raylib  :     > Channels:      2 -> 2
10-23 23:53:52.009 22056 22103 I raylib  :     > Sample rate:   48000 -> 48000
10-23 23:53:52.009 22056 22103 I raylib  :     > Periods size:  1440
10-23 23:53:52.009 22056 22103 I raylib  : Initializing raylib 4.2
10-23 23:53:52.009 22056 22103 I raylib  : Supported raylib modules:
10-23 23:53:52.009 22056 22103 I raylib  :     > rcore:..... loaded (mandatory)
10-23 23:53:52.009 22056 22103 I raylib  :     > rlgl:...... loaded (mandatory)
10-23 23:53:52.009 22056 22103 I raylib  :     > rshapes:... loaded (optional)
10-23 23:53:52.009 22056 22103 I raylib  :     > rtextures:. loaded (optional)
10-23 23:53:52.009 22056 22103 I raylib  :     > rtext:..... loaded (optional)
10-23 23:53:52.009 22056 22103 I raylib  :     > rmodels:... loaded (optional)
10-23 23:53:52.009 22056 22103 I raylib  :     > raudio:.... loaded (optional)
10-23 23:53:52.009 22056 22103 I raylib  : ANDROID: Window orientation set as portrait
10-23 23:53:52.009 22056 22103 W raylib  : ANDROID: Window orientation changed to portrait
10-23 23:53:52.009 22056 22103 I raylib  : ANDROID: App initialized successfully
10-23 23:53:52.198 22056 22103 I raylib  : DISPLAY: Upscaling required: Screen size (400x900) smaller than display size (1080x2298)
10-23 23:53:52.199 22056 22103 I raylib  : DISPLAY: Device initialized successfully
10-23 23:53:52.199 22056 22103 I raylib  :     > Display size: 1080 x 2298
10-23 23:53:52.199 22056 22103 I raylib  :     > Screen size:  400 x 900
10-23 23:53:52.199 22056 22103 I raylib  :     > Render size:  400 x 900
10-23 23:53:52.199 22056 22103 I raylib  :     > Viewport offsets: 23, 0
10-23 23:53:52.199 22056 22103 I raylib  : GL: Supported extensions count: 98
10-23 23:53:52.200 22056 22103 I raylib  : GL: OpenGL device information:
10-23 23:53:52.200 22056 22103 I raylib  :     > Vendor:   Qualcomm
10-23 23:53:52.200 22056 22103 I raylib  :     > Renderer: Adreno (TM) 618
10-23 23:53:52.200 22056 22103 I raylib  :     > Version:  OpenGL ES 3.2 V@0502.0 (GIT@559e78c, Ib9d997268a, 1602616325) (Date:10/13/20)
10-23 23:53:52.200 22056 22103 I raylib  :     > GLSL:     OpenGL ES GLSL ES 3.20
10-23 23:53:52.200 22056 22103 I raylib  : GL: VAO extension detected, VAO functions loaded successfully
10-23 23:53:52.200 22056 22103 I raylib  : GL: NPOT textures extension detected, full NPOT textures supported
10-23 23:53:52.200 22056 22103 I raylib  : GL: ETC1 compressed textures supported
10-23 23:53:52.200 22056 22103 I raylib  : GL: ASTC compressed textures supported
10-23 23:53:52.200 22056 22103 I raylib  : TEXTURE: [ID 1] Texture loaded successfully (1x1 | R8G8B8A8 | 1 mipmaps)
10-23 23:53:52.200 22056 22103 I raylib  : TEXTURE: [ID 1] Default texture loaded successfully
10-23 23:53:52.205 22056 22103 I raylib  : SHADER: [ID 1] Vertex shader compiled successfully
10-23 23:53:52.207 22056 22103 I raylib  : SHADER: [ID 2] Fragment shader compiled successfully
10-23 23:53:52.215 22056 22103 I raylib  : SHADER: [ID 3] Program shader loaded successfully
10-23 23:53:52.215 22056 22103 I raylib  : SHADER: [ID 3] Default shader loaded successfully
10-23 23:53:52.215 22056 22103 I raylib  : RLGL: Render batch vertex buffers loaded successfully in RAM (CPU)
10-23 23:53:52.216 22056 22103 I raylib  : RLGL: Render batch vertex buffers loaded successfully in VRAM (GPU)
10-23 23:53:52.216 22056 22103 I raylib  : RLGL: Default OpenGL state initialized successfully
10-23 23:53:52.229 22056 22103 I raylib  : TEXTURE: [ID 2] Texture loaded successfully (128x128 | GRAY_ALPHA | 1 mipmaps)
10-23 23:53:52.229 22056 22103 I raylib  : FONT: Default font loaded successfully (224 glyphs)
10-23 23:53:52.229 22056 22103 I raylib  : STREAM: Initialized successfully (44100 Hz, 32 bit, Stereo)
10-23 23:53:52.237 22056 22103 I raylib  : FILEIO: [test.mp3] Music file loaded successfully
10-23 23:53:52.237 22056 22103 I raylib  :     > Sample rate:   44100 Hz
10-23 23:53:52.237 22056 22103 I raylib  :     > Sample size:   32 bits
10-23 23:53:52.237 22056 22103 I raylib  :     > Channels:      2 (Stereo)
10-23 23:53:52.237 22056 22103 I raylib  :     > Total frames:  8131968
```
The music file is inside ```android.<project-name>/assets```

**Comment by mackron** [comment]
Did you compile with `-DMA_DEBUG_OUTPUT`? If so, are you able to filter by "miniaudio" and see if that shows anything? I can see from that log that it's falling back to the Null backend (silence) which explains why you can't hear anything, but there's no information about why AAudio and OpenSL failed (`MA_DEBUG_OUTPUT` should show some details about the failure).

**Comment by mackron** [comment]
I don't have an explanation for your case. Without seeing the miniaudio debug output I can't know what's going on. Here's how it's being logged:

```
__android_log_print(ANDROID_LOG_DEBUG, MA_ANDROID_LOG_TAG, "%s: %s", ma_log_level_to_string(level), pMessage);
```

Where `MA_ANDROID_LOG_TAG` is "miniaudio". Assuming the messages are being logged at all, I would expect you should be able to filter by the "miniaudio" tag.

**Comment by planetis-m** [comment]
The defines have changed! You now need to define MA_ANDROID
