### ISSUE TITLE
[core] Mouse input not working on Linux Mint 20.3 Cinnamon KMS/DRM

### ISSUE THREAD

**Issue by sirlordt** [raysan5/raylib#2381]
---

### Issue description

* The demo code_input_mouse not work in DRM mode

### Environment

Linux Mint 20.3 Inside of VMWare 15 workstation.

### Pass to reproduce

- Install Linux Mint 20.3 in a VMWare Workstation 15.5.6 build-16341506

- Open x terminal includes with cinnamon desktop.

```
sudo apt install libasound2-dev mesa-common-dev libx11-dev libxrandr-dev libxi-dev xorg-dev libgl1-mesa-dev libglu1-mesa-dev

# Not compile if not install this first. Headers .h issues

sudo apt install libgbm-dev libgles2-mesa-dev 

cd Desktop

mkdir -p CPP/libraries

cd CPP/libraries

git clone https://github.com/raysan5/raylib.git raylib

cd raylib/src/

make PLATFORM=PLATFORM_DRM

# Compile like charm je je je 

sudo make install

cd ..

cd examples

make PLATFORM=PLATFORM_DRM

# Again compile like charm je je je 

# Press ctrl+alt+space+f1 (In real host/machine is ctrl+alt+f1)

# Made login with your user name and password (Same x session user used to clone the git repo)

cd Desktop/CPP/libraries/raylib/examples/core

./core_input_mouse 

# event with sudo not work

sudo ./core_input_mouse

```
- The mouse not work!!!. But the keyboard, sound and graphics are perfect!!!.

- I added the my user to group input with the same result, the mouse not work.

### Issue Screenshot

![image](https://user-images.githubusercontent.com/4441192/157768667-a85ac517-3359-41cc-a1c6-b182c8fac3b1.png)

![image](https://user-images.githubusercontent.com/4441192/157769640-709719f0-2d7c-461b-8f57-8fbe92ea97ab.png)

**Comment by sirlordt** [comment]
Update.

I ran the core_input_mouse in real machine with the same mouse problem. But work in Intel Integrated Video Card, And NVidia card using nouveau driver. Linux Mint 20.3 Cinnamon.

- Nvidia card nouveau driver

![imagen](https://user-images.githubusercontent.com/4441192/157788413-b6a8ce39-a412-4754-9dc5-03e516fdf9df.png)

- Intel video card. 4k screen.

![imagen](https://user-images.githubusercontent.com/4441192/157788795-a7c9d25c-f245-47f1-8d50-38b296b5b0eb.png)

**Comment by CrezyDud** [comment]
this isnt raylibs issue, more likely glfw's

**Comment by raysan5** [comment]
@sirlordt Actually, KMS/DRM driver has only been tested on Raspberry Pi with RPI OS, other possible configurations have not been tested.

@CrezyDud `PLATFORM_DRM` uses a custom implementation for windowing/inputs, not GLFW.

**Comment by raysan5** [comment]
I'm afraid this is a OS specific issue. Unfortunately PLATFORM_DRM has not been properly tested outside RPI OS Bullseye.

**Comment by sirlordt** [comment]
Sad. Because with the mouse input working is possible develop embedded system not only games.

**Comment by raysan5** [comment]
@sirlordt bussiness opportunity? for the last 9 years I've been working thousands of hours in raylib for free, hardly anyone is ready to pay a cent for raylib and everybody request improvements and issue reviews. Do you want mouse support? Let's sign a $4000 contract for the job and you got it. That's a real bussiness opportunity.

**Comment by sirlordt** [comment]
@raysan5 I'm so sorry. I didn't mean to offend you. I saw you sell programs like rGuiIcons in raylibtech. I think is possible create embedded software for different platform is a options to support the project. I know the difficult keep a open source project in this times and your project is exceptional good.

**Comment by raysan5** [comment]
@sirlordt Excuse me for the harsh answer, it was not appropiate. raylib and the tools are taking a lot of my time for no benefit and it's starting to be really tiring...

About the mouse issue, it seems your Linux version maps mouse inputs to `/dev/input/mouseN` but raylib only checks for `/dev/input/eventN`, I pushed a commit to check for `mouseN`. Let me know if it works.

**Comment by sirlordt** [comment]
@raysan5 hello still not work. but i really appreciate take the time to try to fix the issue. 

I read in twitter your are open to hire in courses. You had online courses about c/c++, maybe in udemy/platzi or another platform?

You are considered open a youtube channel when exclusive content about c/c++ and how create games?.

I mean you had tons knowledge about games you can capitalize in youtube and another platforms.

**Comment by raysan5** [comment]
@sirlordt Hey! Why did you close it? Did you get it working? I don't have the environment to test it so the development of this feature is a big difficult for me.

About the courses, I love teaching but I don't like online, I'm afraid it does not work with my teaching methodology. My classes are very interactive with the students, asking questions all the time and making students thing about the lessons, that's impossible to do online... but maybe at some point I try to publish some online course or class, I got a Twitch and a Youtube channel.

**Comment by sirlordt** [comment]
@raysan5 Is not working yet.  

I sorry. I thinked you are really busy to resolv this issue!!. 

I to reopen again!!!.

Thanks!!!

**Comment by raysan5** [comment]
Just pushed a possible fix but I'm afraid I'm closing this issue, I can't keep developing it without the proper environment and the cost to set and debug in the right environment properly does not worth the time.

Anyone facing this problem and finding this issue with the right environment and knowledge should review it. The issue is related to the events system, only the `event<n>` devices are scanned while some Linux OS versions map the mouse as `mouse<n>` devices instead of `event<n>`. It just needs to be properly debugged.

Estimated time to fix the issue: 10 minutes.
Estimated time to setup the right environment and debugger: 5 hours.

**Comment by jetoge** [comment]
I've been taking a look at this bug, and I'm not sure what's causing it.

First of all, it is not replicable on Linux Mint 21, both XFCE and Cinnamon, which it seems to work properly.

Second of all, on 20.3, the bug only affects 3D camera movements, which also includes WASD movement, mouse input does work properly. Gamepad also does not seem to work properly, on both versions of Linux Mint, but it could be a driver issue with the Xbox Controller not resolved on my end.

That WASD movement does also not work did seem a little strange, but the check to allow for that, in rcamera.h:451: IsGamepadAvailable(0) returns false, so, it should be triggering that part of the code properly. I am a little stuck with that, so if anyone has any suggestions on how to debug that, let me know.
