### ISSUE TITLE
[core] CAMERA_THIRD_PERSON mode broken

### ISSUE THREAD

**Issue by astlin** [raysan5/raylib#742]
Hi. When camera is set to CAMERA_THIRD_PERSON mode then it flies somewhere up. Any fix or workaround?

**Comment by SolarLune** [comment]
Perhaps you should post some code to look at to determine where the issue might lie? Like, does the same issue happen with a minimal example with just creating the camera and setting the mode?

**Comment by astlin** [comment]
Sure. 

```
#include <raylib.h>

int main() {
    int screenWidth = 1024;
    int screenHeight = 768;

    InitWindow(screenWidth, screenHeight, "3rd person");

    Camera camera = { 0 };
    camera.position = (Vector3){ 100.0f, 100.0f, 0.0f };
    camera.target = (Vector3){ 0.0f, 0.0f, 0.0f };
    camera.up = (Vector3){ 0.0f, 1.0f, 0.0f };
    camera.fovy = 45.0f;
    camera.type = CAMERA_PERSPECTIVE;
    SetCameraMode(camera, CAMERA_THIRD_PERSON);

    SetTargetFPS(60);
    while (!WindowShouldClose()) {
        UpdateCamera(&camera);
        BeginDrawing();

        ClearBackground(RAYWHITE);

        BeginMode3D(camera);
            DrawGrid(100, 64.0f);        // Draw a grid
        EndMode3D();

        DrawRectangle( 10, 10, 220, 110, Fade(SKYBLUE, 0.5f));
        DrawRectangleLines( 10, 10, 220, 110, BLUE);

        DrawText(std::to_string(GetFrameTime()).c_str(), 20, 20, 10, DARKGRAY);

        DrawText(std::to_string(camera.target.x).c_str(), 20, 40, 10, DARKGRAY);
        DrawText(std::to_string(camera.target.y).c_str(), 20, 50, 10, DARKGRAY);
        DrawText(std::to_string(camera.target.z).c_str(), 20, 60, 10, DARKGRAY);

        DrawText(std::to_string(camera.position.x).c_str(), 20, 80, 10, DARKGRAY);
        DrawText(std::to_string(camera.position.y).c_str(), 20, 90, 10, DARKGRAY);
        DrawText(std::to_string(camera.position.z).c_str(), 20, 100, 10, DARKGRAY);

        EndDrawing();
    }

    CloseWindow();
    return 0;
}
```
After starting we see grid rapidly moves away and camera coordinates changing.

**Comment by raysan5** [comment]
Issue is on `camera.h` module, most probably [here](https://github.com/raysan5/raylib/blob/master/src/camera.h#L424).

This module should be redesigned... I don't like it... :(

**Comment by astlin** [comment]
I've tried some debugging and the problem is definitely in this block https://github.com/raysan5/raylib/blob/c200642887a8a5a4fd38168aee224dc9fc9906ab/src/camera.h#L470

**Comment by lenormf** [comment]
Why was this issue removed from the milestone? It seems serious enough that it should be fixed ASAP.

**Comment by raysan5** [comment]
Sorry, don' have the time to dig into it for milestone 2.5 but Pull Request are welcome.

**Comment by lenormf** [comment]
The issue seems to stem from this block:

https://github.com/raysan5/raylib/blob/c200642887a8a5a4fd38168aee224dc9fc9906ab/src/camera.h#L437,L439

When I comment it, the camera remains stable and usable. What is this bit doing, exactly?

**Comment by raysan5** [comment]
It positions the camera target at a certain distance from camera position.

Probably issue is just a simple thing but it requires some time for review...

**Comment by raysan5** [comment]
Some work done on commit https://github.com/raysan5/raylib/commit/cc1dd6b410ca8c6ba2b9dd1a923c7740034cd1d9 but this issue still requires some work... any mathematician in the room?

**Comment by raysan5** [comment]
`CAMERA_THIRD_PERSON` reviewed on PR https://github.com/raysan5/raylib/pull/866

An usage example will be added hopefully soon!
